/*

 ENDSCREEN.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\dietr\Documents\GameDev\osu_game_jam_4162021\assets\background_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define endscreenWidth 20
#define endscreenHeight 18
#define endscreenBank 0

extern unsigned char endscreen[];

/* End of ENDSCREEN.H */
