/*

 LEVEL_ONE_COMPLETE.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\dietr\Documents\GameDev\osu_game_jam_4162021\assets\background_tileset.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level_one_completeWidth 20
#define level_one_completeHeight 18
#define level_one_completeBank 0

extern unsigned char level_one_complete[];

/* End of LEVEL_ONE_COMPLETE.H */
